" ==============
"    vim-plug
" ==============
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
	  \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
	Plug 'airblade/vim-rooter'
	Plug 'jiangmiao/auto-pairs'
	Plug 'preservim/nerdtree'
	Plug 'prabirshrestha/async.vim'
	Plug 'prabirshrestha/vim-lsp'
	Plug 'mattn/vim-lsp-settings'
	Plug 'prabirshrestha/asyncomplete.vim'
	Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

" ==============
"    vim-lsp
" ==============
let g:lsp_settings = {
\  'clangd': {'cmd': ['clangd', '--enable-config', '--background-index']},
\}

" ==============
"    NERDTree
" ==============
" Close NERDTree if it's the only window left open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") &&
  \ b:NERDTree.isTabTree()) | q | endif
" Automatically launch NERDTree
autocmd VimEnter * NERDTree
" NERDTree shouldn't be the default window
autocmd VimEnter * wincmd p
" Set working directory to the file's dir
autocmd BufEnter * lcd %:p:h
hi NERDTreeCWD ctermfg=green

" ==============
"    personal
" ==============
set number
set mouse=
set ttymouse=
hi LineNr ctermfg=grey
hi Comment ctermfg=grey
hi Directory ctermfg=cyan
hi SignColumn ctermbg=NONE
hi CursorLine ctermfg=NONE
hi over80 ctermbg=red ctermfg=white
hi VertSplit cterm=NONE ctermbg=NONE
hi Search ctermbg=yellow ctermfg=black
hi Visual ctermbg=magenta ctermfg=white
hi Pmenu cterm=NONE ctermbg=black ctermfg=white
hi StatusLine cterm=NONE ctermbg=black ctermfg=white
hi StatusLineNC cterm=NONE ctermbg=black ctermfg=grey
hi SpellBad cterm=underline ctermbg=NONE ctermfg=red
hi CursorColumn cterm=NONE ctermbg=yellow ctermfg=black
call matchadd("over80", "\\%>80v.\\+", 10, 4)
